name: "sams_subs_dw"
version: "1.0.0"
profile: "sams_subs_dw"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
   - "target"
   - "dbt_packages"

models:
   sams_subs_dw:
      final:
         +materialized: table
         +schema: dw_sams_subs
      example:
         +materialized: view
         +schema: dw_sams_subs
